### ISSUE TITLE
horizontalAlignment broken for registers

### ISSUE THREAD

**Issue by benoitjchevalier** [predixdesignsystem/px-vis#105]
what the title says
tried it on v3, not sure about v2

**Comment by ppeyro** [comment]
Looks like category-register-config may be broken for other attributes too in both 2.x and 3.x.

Tried the following with vis 2.2+radar 2.2 and none seem to work:
horizontalAlignment, tooltipStyle, height, preventMuting

**Comment by tvluong051** [comment]
+1
I found that px-vis-register set a `max-width` on `registerWrap` element which lead to the fact that `horizontalAlignment` do not work properly.
In older version (like 1.x.x), it works because px-vis-register set `width` instead of `max-width`.
Could you please fix that bug please!
