### ISSUE TITLE
[Navigator] Update "range" property on navigator

### ISSUE THREAD

**Issue by nonmetalhail** [predixdesignsystem/px-vis#112]
With the release of v3 of Rangpicker, the range object no longer exists. Instead, users must provide a moment object for the to and from. We should adjust the navigator accordingly and either accept the moment objects, or require the dev to convert them to a unix timestamp which we are currently doing internally.

**Comment by benoitjchevalier** [comment]
range will be deleted in favor of `chartExtents`
