### ISSUE TITLE
Hang colors from the window

### ISSUE THREAD

**Issue by benoitjchevalier** [predixdesignsystem/px-vis#115]
What if we hang the colors from the window rather than have each chart try to read the theme? 

We would do the job only once and that should be a really big help for all those charts we see starting drawing in black and then picking up the colors (i.e we should only see that once rather than every time a chart is created and appended)

**Comment by nonmetalhail** [comment]
But then the theme would have to ship with js to do this. The reason to try using only the theme was to make it easier to update or change colors

**Comment by benoitjchevalier** [comment]
can't we use the current mechanism we have, but only once in one global place and store the colors in a global `seriesColorList` instead of redoing it for every chart?

**Comment by nonmetalhail** [comment]
Hmm, that's a good idea. However, one could specify different theme vars for different charts so we'd still have to check the theme vars, but could use the stored one for first paint

**Comment by benoitjchevalier** [comment]
👍
