### ISSUE TITLE
Increase the types of scales supported

### ISSUE THREAD

**Issue by nonmetalhail** [predixdesignsystem/px-vis#14]
d3 scales can support more types of scales. We should add them:
https://github.com/d3/d3/wiki/Quantitative-Scales

**Comment by nonmetalhail** [comment]
Feature request for logs via the forums. Should do this for v1.1.0

**Comment by labolanimichele** [comment]
Hi - I believe we are currently supporting only linear axes for 2-D charts. Would it be possible to add the possibility of logarithmic axes?

**Comment by nonmetalhail** [comment]
Ok, added in vis v4.7.0. The TS & XY got a patch bump too and should pick up vis 4.7.0 if you do a bower install. 

To use, you'll just have to specify you axis type to `"log"`
